name: tram
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6  
  - pandas=1.0.5
  - pandas-plink=2.0.4
  - numpy=1.19.1
  - matplotlib=3.3.1
  - scipy=1.5.0
  - assocplots=0.0.2
  - seaborn=0.11.0
